parser: babel-eslint

plugins:
  - import
  - react
  - jsx-a11y

env:
  node: true,
  browser: true,
  es6: true

rules:
  indent: [2, 4, { SwitchCase: 1 }]
  react/jsx-indent: [2, 4]
  react/jsx-indent-props: [2, 4]
  react/jsx-first-prop-new-line: [2, never]
  react/prop-types: [0]
  react/prefer-stateless-function: [0]
  func-names: [2, 'never']
  arrow-parens: [2, 'as-needed']
  arrow-body-style: [0, 'as-needed']
  max-len: [2, 620, 4]
  no-tabs: [2]
  no-useless-escape: [0]
  no-useless-computed-key: [0]
  semi: [2, never]

parserOptions:
  ecmaVersion: 8
  sourceType: module

  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true

settings:
  import/resolver:
    node:
      moduleDirectory: ['node_modules', './src']