export const ADD_NOTE = 'ADD_NOTE'
export const ADD_POINT = 'ADD_POINT'
export const CHANGE_NOTE = 'CHANGE_NOTE'
export const CHANGE_POINT = 'CHANGE_POINT'
export const DELETE_NOTE = 'DELETE_NOTE'
export const DELETE_POINT = 'DELETE_POINT'
